
spring:
    rabbitmq:
        host: 118.89.158.164
        port: 5672
        username: lumia
        password: lumia
        publisher-confirms: true
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
    redis:
        host: 118.89.158.164
        password: LumiaQian
        port: 6379
    datasource:
        name: anjuhome
        url:  jdbc:mysql://localhost:3306/anjuhome?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: admin
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        tWhileIdestle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql